#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
17_evaluate_standardized_scores.py

Evaluate standardized zero-shot model scores generated by:
16_standardize_model_scores.py

Input
-----
data_processed/model_scores_standardized/all_model_scores_long.csv

Optional structure label table:
data_processed/sa_prot_structures/final_structure_source_by_residue.csv

Main outputs
------------
metrics_by_assay_available.csv
metrics_by_model_available.csv
metrics_by_virus_available.csv
metrics_by_structure_source_available.csv
all_model_scores_common.csv
metrics_by_assay_common.csv
metrics_by_model_common.csv
metrics_by_virus_common.csv
evaluation_summary.txt

Meaning
-------
available:
    Each model is evaluated on all variants it successfully scored.

common:
    Only variants that have scores from all selected models are retained.
    This is the fairer model-to-model comparison set.

Typical command
---------------
python scripts/analysis/18_evaluate_standardized_scores.py \
  --scores data_processed/model_scores_standardized/all_model_scores_long.csv \
  --label-table data_processed/sa_prot_structures/final_structure_source_by_residue.csv \
  --out-dir data_processed/evaluation_3models \
  --models ESM1v,ESM2,SaProt \
  --ks 10,20,0.1
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import List

import numpy as np
import pandas as pd


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--scores", required=True,
                   help="all_model_scores_long.csv from standardization step")
    p.add_argument("--label-table", default=None,
                   help="final_structure_source_by_residue.csv")
    p.add_argument("--out-dir", required=True)
    p.add_argument("--models", default="auto",
                   help="Comma-separated model names, e.g. ESM1v,ESM2,SaProt. Use auto for all.")
    p.add_argument("--key-cols", default="DMS_name,pdb_id,chains_raw,esm_mut",
                   help="Key columns used to define the common variant intersection.")
    p.add_argument("--ks", default="10,20,0.1",
                   help="Comma-separated top-k settings. 10 means top 10; 0.1 means top 10%%.")
    p.add_argument("--min-n", type=int, default=10)
    p.add_argument("--invert-model", action="append", default=[],
                   help="Model name whose score should be multiplied by -1 before evaluation.")
    return p.parse_args()


def parse_list(x: str) -> List[str]:
    if x == "auto":
        return []
    return [i.strip() for i in x.split(",") if i.strip()]


def parse_ks(x: str) -> List[float]:
    out = []
    for item in x.split(","):
        item = item.strip()
        if item:
            out.append(float(item))
    return out


def infer_virus(dms_name: str) -> str:
    s = str(dms_name)
    if s.startswith("COVID"):
        return "COVID-19"
    if s.startswith("HIV"):
        return "HIV"
    if s.startswith("Influenza"):
        return "Influenza"
    return s.split("_")[0]


def length_bin(x) -> str:
    try:
        v = float(x)
    except Exception:
        return "unknown"
    if v <= 300:
        return "<=300"
    if v <= 700:
        return "301-700"
    return ">700"


def topk_recall(y_true: np.ndarray, y_pred: np.ndarray, k_spec: float) -> float:
    n = len(y_true)
    if n == 0:
        return np.nan

    if 0 < k_spec < 1:
        k = int(np.ceil(n * k_spec))
    else:
        k = int(k_spec)

    k = max(1, min(k, n))
    actual = set(np.argsort(-y_true)[:k])
    pred = set(np.argsort(-y_pred)[:k])
    return len(actual & pred) / k


def compute_metrics(df: pd.DataFrame, group_cols: List[str], ks: List[float], min_n: int) -> pd.DataFrame:
    rows = []
    for keys, g in df.groupby(group_cols, dropna=False):
        if not isinstance(keys, tuple):
            keys = (keys,)

        gg = g[["DMS_score", "model_score_eval"]].dropna()
        n = len(gg)

        rec = dict(zip(group_cols, keys))
        rec["n"] = n

        if n >= min_n and gg["DMS_score"].nunique() > 1 and gg["model_score_eval"].nunique() > 1:
            rec["spearman"] = gg["DMS_score"].corr(gg["model_score_eval"], method="spearman")
            rec["pearson"] = gg["DMS_score"].corr(gg["model_score_eval"], method="pearson")

            y = gg["DMS_score"].to_numpy(dtype=float)
            p = gg["model_score_eval"].to_numpy(dtype=float)

            for k in ks:
                label = f"topk_recall_{str(k).replace('.', 'p')}"
                rec[label] = topk_recall(y, p, k)
        else:
            rec["spearman"] = np.nan
            rec["pearson"] = np.nan
            for k in ks:
                label = f"topk_recall_{str(k).replace('.', 'p')}"
                rec[label] = np.nan

        rows.append(rec)

    return pd.DataFrame(rows)


def summarize_metrics(metrics: pd.DataFrame, group_cols: List[str]) -> pd.DataFrame:
    if metrics.empty:
        return pd.DataFrame()

    metric_cols = [
        c for c in metrics.columns
        if c not in set(group_cols + ["DMS_name", "n", "virus", "final_source", "length_bin"])
        and pd.api.types.is_numeric_dtype(metrics[c])
    ]

    agg = {
        "DMS_name": "nunique",
        "n": "mean",
    }

    named = {
        "n_assays": ("DMS_name", "nunique"),
        "mean_n_variants": ("n", "mean"),
    }

    for c in metric_cols:
        named[f"mean_{c}"] = (c, "mean")
        named[f"median_{c}"] = (c, "median")

    return metrics.groupby(group_cols, dropna=False).agg(**named).reset_index()


def add_structure_labels(scores: pd.DataFrame, label_table: str | None) -> pd.DataFrame:
    scores = scores.copy()

    if not label_table:
        return scores
    p = Path(label_table)
    if not p.exists():
        return scores

    labels = pd.read_csv(p)

    # First try DMS_name + site_raw(fasta_pos)
    if "site_raw" in scores.columns and {"DMS_name", "fasta_pos"}.issubset(labels.columns):
        lab1_cols = [
            "DMS_name", "fasta_pos", "final_source", "has_pdb_coord",
            "af2_plddt", "af2_pass_plddt", "sequence_length", "wt_aa"
        ]
        lab1_cols = [c for c in lab1_cols if c in labels.columns]
        lab1 = labels[lab1_cols].drop_duplicates(subset=["DMS_name", "fasta_pos"]).copy()
        lab1 = lab1.rename(columns={"fasta_pos": "site_raw"})
        scores = scores.merge(lab1, on=["DMS_name", "site_raw"], how="left", suffixes=("", "_label1"))

    # Fallback: DMS_name + seq_pos_1(wt_local_pos)
    need_fallback = "final_source" not in scores.columns or scores["final_source"].isna().any()
    if need_fallback and "seq_pos_1" in scores.columns and {"DMS_name", "wt_local_pos"}.issubset(labels.columns):
        lab2_cols = [
            "DMS_name", "wt_local_pos", "final_source", "has_pdb_coord",
            "af2_plddt", "af2_pass_plddt", "sequence_length", "wt_aa"
        ]
        lab2_cols = [c for c in lab2_cols if c in labels.columns]
        lab2 = labels[lab2_cols].drop_duplicates(subset=["DMS_name", "wt_local_pos"]).copy()
        lab2 = lab2.rename(columns={
            "wt_local_pos": "seq_pos_1",
            "final_source": "final_source_local",
            "has_pdb_coord": "has_pdb_coord_local",
            "af2_plddt": "af2_plddt_local",
            "af2_pass_plddt": "af2_pass_plddt_local",
            "sequence_length": "sequence_length_local",
            "wt_aa": "wt_aa_local",
        })
        scores = scores.merge(lab2, on=["DMS_name", "seq_pos_1"], how="left")

        # Fill missing from local fallback.
        fill_pairs = [
            ("final_source", "final_source_local"),
            ("has_pdb_coord", "has_pdb_coord_local"),
            ("af2_plddt", "af2_plddt_local"),
            ("af2_pass_plddt", "af2_pass_plddt_local"),
            ("sequence_length", "sequence_length_local"),
            ("wt_aa", "wt_aa_local"),
        ]
        for a, b in fill_pairs:
            if b in scores.columns:
                if a not in scores.columns:
                    scores[a] = scores[b]
                else:
                    scores[a] = scores[a].where(scores[a].notna(), scores[b])

    return scores


def make_common_intersection(scores: pd.DataFrame, models: List[str], key_cols: List[str]) -> pd.DataFrame:
    usable_keys = [c for c in key_cols if c in scores.columns]
    if not usable_keys:
        usable_keys = ["DMS_name", "esm_mut"] if "esm_mut" in scores.columns else ["DMS_name", "mut_name"]

    # Drop rows with missing key components.
    temp = scores.dropna(subset=usable_keys + ["model", "model_score_eval", "DMS_score"]).copy()

    counts = temp.groupby(usable_keys)["model"].nunique().reset_index(name="n_models")
    common_keys = counts[counts["n_models"] == len(models)][usable_keys]
    common = temp.merge(common_keys, on=usable_keys, how="inner")
    return common


def main():
    args = parse_args()
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)

    scores = pd.read_csv(args.scores)

    if "DMS_score" not in scores.columns:
        raise ValueError("Input scores must contain DMS_score.")
    if "model_score" not in scores.columns:
        raise ValueError("Input scores must contain model_score.")
    if "model" not in scores.columns:
        raise ValueError("Input scores must contain model.")

    wanted_models = parse_list(args.models)
    if wanted_models:
        scores = scores[scores["model"].isin(wanted_models)].copy()
        models = wanted_models
    else:
        models = sorted(scores["model"].dropna().unique().tolist())

    scores = add_structure_labels(scores, args.label_table)

    scores["virus"] = scores["DMS_name"].map(infer_virus)
    if "sequence_length" not in scores.columns or scores["sequence_length"].isna().all():
        if "wt_sequence" in scores.columns:
            scores["sequence_length"] = scores["wt_sequence"].astype(str).str.len()
        else:
            scores["sequence_length"] = np.nan
    scores["length_bin"] = scores["sequence_length"].map(length_bin)

    scores["model_score_eval"] = pd.to_numeric(scores["model_score"], errors="coerce")
    for m in args.invert_model:
        scores.loc[scores["model"] == m, "model_score_eval"] *= -1

    scores.to_csv(out / "all_model_scores_with_labels_available.csv", index=False)

    ks = parse_ks(args.ks)

    # Available-set evaluation.
    m_assay = compute_metrics(scores, ["virus", "DMS_name", "model"], ks, args.min_n)
    m_assay.to_csv(out / "metrics_by_assay_available.csv", index=False)

    m_model = summarize_metrics(m_assay, ["model"])
    m_model.to_csv(out / "metrics_by_model_available.csv", index=False)

    m_virus = summarize_metrics(m_assay, ["virus", "model"])
    m_virus.to_csv(out / "metrics_by_virus_available.csv", index=False)

    if "final_source" in scores.columns:
        m_source_assay = compute_metrics(
            scores.dropna(subset=["final_source"]),
            ["virus", "DMS_name", "model", "final_source"],
            ks,
            args.min_n,
        )
        m_source_assay.to_csv(out / "metrics_by_assay_structure_source_available.csv", index=False)
        m_source = summarize_metrics(m_source_assay, ["model", "final_source"])
        m_source.to_csv(out / "metrics_by_structure_source_available.csv", index=False)

    m_len_assay = compute_metrics(scores, ["virus", "DMS_name", "model", "length_bin"], ks, args.min_n)
    m_len_assay.to_csv(out / "metrics_by_assay_length_bin_available.csv", index=False)
    m_len = summarize_metrics(m_len_assay, ["model", "length_bin"])
    m_len.to_csv(out / "metrics_by_length_bin_available.csv", index=False)

    # Common-intersection evaluation.
    key_cols = [c.strip() for c in args.key_cols.split(",") if c.strip()]
    common = make_common_intersection(scores, models, key_cols)
    common.to_csv(out / "all_model_scores_common.csv", index=False)

    cm_assay = compute_metrics(common, ["virus", "DMS_name", "model"], ks, args.min_n)
    cm_assay.to_csv(out / "metrics_by_assay_common.csv", index=False)

    cm_model = summarize_metrics(cm_assay, ["model"])
    cm_model.to_csv(out / "metrics_by_model_common.csv", index=False)

    cm_virus = summarize_metrics(cm_assay, ["virus", "model"])
    cm_virus.to_csv(out / "metrics_by_virus_common.csv", index=False)

    # Summary text.
    with open(out / "evaluation_summary.txt", "w") as f:
        f.write("Models: " + ",".join(models) + "\n")
        f.write(f"Available rows: {len(scores)}\n")
        f.write(f"Common rows: {len(common)}\n")
        f.write("\nAvailable model counts:\n")
        f.write(scores["model"].value_counts().to_string() + "\n")
        f.write("\nCommon model counts:\n")
        f.write(common["model"].value_counts().to_string() + "\n")
        f.write("\nAvailable metrics by model:\n")
        f.write(m_model.to_string(index=False) + "\n")
        f.write("\nCommon metrics by model:\n")
        f.write(cm_model.to_string(index=False) + "\n")

    print("[OK] Wrote evaluation outputs to:", out)
    print("\nAvailable model counts:")
    print(scores["model"].value_counts())
    print("\nCommon model counts:")
    print(common["model"].value_counts())
    print("\nAvailable metrics by model:")
    print(m_model.to_string(index=False))
    print("\nCommon metrics by model:")
    print(cm_model.to_string(index=False))


if __name__ == "__main__":
    main()
