#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
13_prepare_saprot_inputs.py

Prepare SaProt-ready sequence/structure manifests after PDB/AF2 structure-source assignment.

This script does NOT run SaProt and does NOT run Foldseek directly.
It prepares clean inputs and job files for the next SaProt/Foldseek step.

Inputs expected from previous steps
-----------------------------------
1) final_structure_source_by_residue.csv
   Generated by 12_collect_af2_and_merge_fill.py

2) af2_prediction_summary.csv
   Generated by 12_collect_af2_and_merge_fill.py

3) dms_reference_with_pdb.csv
   Your assay/reference metadata table

Outputs
-------
1) saprot_input_manifest.csv
   One row per DMS_name / pdb_id / pdb_chain_id entry.

2) saprot_unique_sequences.fasta
   Unique WT sequences used by SaProt.

3) saprot_structure_jobs.tsv
   Which single-chain structure file should be passed to Foldseek for each SaProt input.

4) saprot_mask_positions.tsv
   Positions whose structure token should later be masked as "#", mainly residue_only positions.

5) structures_for_foldseek/*.pdb
   Single-chain PDB files extracted from PDB/mmCIF or AF2 rank_001 PDB.

6) run_foldseek_saprot.sh
   A draft Foldseek command list.

Typical command
---------------
python scripts/structure/13_prepare_saprot_inputs.py \
  --final-source data_processed/sa_prot_structures/final_structure_source_by_residue.csv \
  --af2-summary data_processed/sa_prot_structures/af2_prediction_summary.csv \
  --dms-ref data_processed/dms_reference_with_pdb.csv \
  --struct-dir raw_data/pdb_structs \
  --out-dir data_processed/saprot_inputs \
  --prefer af2_for_any_fill

Structure selection policy
--------------------------
--prefer pdb_if_all_dms_pdb
    Use PDB chain if all DMS sites are PDB-covered.
    Use AF2 full structure if any DMS site needs AF2_fill/residue_only and AF2 is available.

--prefer af2_for_any_fill
    Same as above, but explicitly prefers AF2 full structure whenever any DMS site is not PDB-covered.
    This is recommended for a first SaProt run because it avoids constructing artificial PDB+AF2 hybrid structures.

--prefer af2_all
    Use AF2 rank_001 structure whenever available for all entries.

Important note
--------------
This script does NOT create a hybrid PDB+AF2 coordinate file.
For SaProt/Foldseek, a single internally consistent structure is safer than directly stitching
PDB and AF2 coordinates into one artificial file.
"""

from __future__ import annotations

import argparse
import glob
import hashlib
import os
import re
from pathlib import Path
from typing import Optional, Dict, List

import pandas as pd

try:
    from Bio.PDB import PDBParser, MMCIFParser, PDBIO, Select
except Exception as e:
    PDBParser = None
    MMCIFParser = None
    PDBIO = None
    Select = object


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--final-source", required=True,
                   help="final_structure_source_by_residue.csv")
    p.add_argument("--af2-summary", required=True,
                   help="af2_prediction_summary.csv")
    p.add_argument("--dms-ref", required=True,
                   help="dms_reference_with_pdb.csv")
    p.add_argument("--struct-dir", required=True,
                   help="Directory containing original PDB/mmCIF files")
    p.add_argument("--out-dir", required=True,
                   help="Output directory")
    p.add_argument("--prefer",
                   choices=["pdb_if_all_dms_pdb", "af2_for_any_fill", "af2_all"],
                   default="af2_for_any_fill")
    p.add_argument("--plddt-threshold", type=float, default=70.0)
    return p.parse_args()


def md5_seq(seq: str) -> str:
    return hashlib.md5(seq.encode("utf-8")).hexdigest()


def clean_seq(x) -> str:
    if pd.isna(x):
        return ""
    return re.sub(r"\s+", "", str(x).strip().upper())


def wrap_fasta(seq: str, width: int = 80) -> str:
    return "\n".join(seq[i:i + width] for i in range(0, len(seq), width))


def extract_start_pos(notes) -> int:
    if pd.isna(notes):
        return 1
    m = re.search(r"start_pos=(\d+)", str(notes))
    return int(m.group(1)) if m else 1


def locate_structure_file(struct_dir: str, structure_file: Optional[str], pdb_id: str) -> Optional[str]:
    if structure_file and not pd.isna(structure_file):
        p = Path(struct_dir) / str(structure_file)
        if p.exists():
            return str(p)

    candidates = []
    for ext in ["cif", "mmcif", "pdb", "ent"]:
        candidates.extend(glob.glob(os.path.join(struct_dir, f"{pdb_id}*.{ext}")))

    if candidates:
        return sorted(set(candidates))[0]

    tail = str(pdb_id).split("_")[-1]
    if re.fullmatch(r"[0-9A-Za-z]{4}", tail):
        for ext in ["cif", "mmcif", "pdb", "ent"]:
            candidates.extend(glob.glob(os.path.join(struct_dir, f"*{tail}*.{ext}")))
    return sorted(set(candidates))[0] if candidates else None


class ChainSelect(Select):
    def __init__(self, chain_id: str):
        self.chain_id = chain_id

    def accept_chain(self, chain):
        return chain.id == self.chain_id


def load_structure_try_modes(path: str, chain_id: str):
    """
    For mmCIF, try both auth_chains=True and False because RCSB pages often show
    label_asym_id with auth_asym_id in brackets.
    """
    ext = Path(path).suffix.lower()

    if PDBParser is None:
        raise RuntimeError("Biopython Bio.PDB is required for chain extraction.")

    attempts = []
    if ext in [".cif", ".mmcif"]:
        attempts = [
            ("cif_auth", MMCIFParser(QUIET=True, auth_chains=True)),
            ("cif_label", MMCIFParser(QUIET=True, auth_chains=False)),
        ]
    else:
        attempts = [("pdb", PDBParser(QUIET=True))]

    last_chains = []
    for mode, parser in attempts:
        structure = parser.get_structure("x", path)
        model = next(structure.get_models())
        chains = [c.id for c in model.get_chains()]
        last_chains = chains
        if chain_id in chains:
            return structure, mode, chain_id

    # fallback: if only one chain exists, use it
    if len(last_chains) == 1:
        mode, parser = attempts[-1]
        structure = parser.get_structure("x", path)
        return structure, mode + "_single_chain_fallback", last_chains[0]

    raise ValueError(f"Chain {chain_id} not found in {os.path.basename(path)}. Available chains: {last_chains}")


def extract_single_chain_pdb(input_path: str, chain_id: str, output_path: str) -> Dict:
    structure, mode, actual_chain = load_structure_try_modes(input_path, chain_id)
    io = PDBIO()
    io.set_structure(structure)
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    io.save(output_path, ChainSelect(actual_chain))
    return {"parser_mode": mode, "actual_chain_id": actual_chain}


def choose_structure(row: pd.Series, af2_lookup: Dict[str, str], struct_dir: str, prefer: str) -> Dict:
    seq_md5 = row["seq_md5"]
    has_af2 = seq_md5 in af2_lookup and isinstance(af2_lookup[seq_md5], str) and os.path.exists(af2_lookup[seq_md5])

    n_dms = int(row.get("n_dms_sites", 0))
    n_pdb = int(row.get("n_dms_PDB", 0))
    n_af2 = int(row.get("n_dms_AF2_fill", 0))
    n_res = int(row.get("n_dms_residue_only", 0))

    all_dms_pdb = (n_dms > 0 and n_pdb == n_dms)

    # Decide mode.
    if prefer == "af2_all" and has_af2:
        return {
            "structure_mode": "AF2_full",
            "source_structure_path": af2_lookup[seq_md5],
            "source_chain_id": "A",
            "reason": "prefer=af2_all and AF2 rank_001 exists",
        }

    if all_dms_pdb:
        pdb_path = locate_structure_file(
            struct_dir=struct_dir,
            structure_file=row.get("structure_file"),
            pdb_id=row.get("pdb_id"),
        )
        return {
            "structure_mode": "PDB_chain",
            "source_structure_path": pdb_path,
            "source_chain_id": row.get("pdb_chain_id"),
            "reason": "all DMS sites covered by experimental structure",
        }

    if has_af2:
        return {
            "structure_mode": "AF2_full",
            "source_structure_path": af2_lookup[seq_md5],
            "source_chain_id": "A",
            "reason": "some DMS sites not PDB-covered; use internally consistent AF2 full structure",
        }

    pdb_path = locate_structure_file(
        struct_dir=struct_dir,
        structure_file=row.get("structure_file"),
        pdb_id=row.get("pdb_id"),
    )
    return {
        "structure_mode": "PDB_partial_no_AF2",
        "source_structure_path": pdb_path,
        "source_chain_id": row.get("pdb_chain_id"),
        "reason": "AF2 unavailable; fallback to PDB partial structure",
    }


def main():
    args = parse_args()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    struct_out = out_dir / "structures_for_foldseek"
    struct_out.mkdir(parents=True, exist_ok=True)

    final = pd.read_csv(args.final_source)
    af2_summary = pd.read_csv(args.af2_summary)
    dms_ref = pd.read_csv(args.dms_ref)

    # Sequence metadata from dms_ref.
    dms_ref = dms_ref.copy()
    dms_ref["selected_wt_sequence"] = dms_ref.apply(
        lambda r: clean_seq(r["best_wt_sequence"]) if "best_wt_sequence" in r and clean_seq(r.get("best_wt_sequence")) else clean_seq(r.get("wt_sequence")),
        axis=1
    )
    dms_ref["seq_md5"] = dms_ref["selected_wt_sequence"].map(md5_seq)
    dms_ref["start_pos_from_ref"] = dms_ref.get("notes", pd.Series([""] * len(dms_ref))).map(extract_start_pos)

    # DMS site source counts.
    dms_sites = final[final["is_dms_site"] == 1].copy()
    count = (
        dms_sites.groupby(["DMS_name", "pdb_id", "pdb_chain_id", "final_source"], dropna=False)
        .size()
        .reset_index(name="n")
        .pivot_table(
            index=["DMS_name", "pdb_id", "pdb_chain_id"],
            columns="final_source",
            values="n",
            fill_value=0,
        )
        .reset_index()
    )
    count.columns.name = None
    for col in ["PDB", "AF2_fill", "residue_only"]:
        if col not in count.columns:
            count[col] = 0
        count[f"n_dms_{col}"] = count[col].astype(int)
        count = count.drop(columns=[col])

    count["n_dms_sites"] = count[["n_dms_PDB", "n_dms_AF2_fill", "n_dms_residue_only"]].sum(axis=1)

    # Representative structure file from final table.
    rep_cols = ["DMS_name", "pdb_id", "pdb_chain_id", "structure_file"]
    rep_cols = [c for c in rep_cols if c in final.columns]
    rep = final[rep_cols].drop_duplicates()

    # Merge metadata.
    meta_cols = [
        "DMS_name", "pdb_id", "pdb_chain_id", "selected_wt_sequence", "seq_md5",
        "start_pos_from_ref"
    ]
    for c in ["best_wt_sequence", "wt_sequence", "notes"]:
        if c in dms_ref.columns and c not in meta_cols:
            meta_cols.append(c)

    manifest = count.merge(dms_ref[meta_cols].drop_duplicates(), on=["DMS_name", "pdb_id", "pdb_chain_id"], how="left")
    manifest = manifest.merge(rep, on=["DMS_name", "pdb_id", "pdb_chain_id"], how="left")

    # AF2 lookup by seq_md5.
    af2_summary = af2_summary.copy()
    af2_lookup = {}
    if "seq_md5" in af2_summary.columns and "rank1_pdb_path" in af2_summary.columns:
        for _, r in af2_summary.iterrows():
            p = r.get("rank1_pdb_path")
            if isinstance(p, str) and os.path.exists(p):
                af2_lookup[str(r["seq_md5"])] = p

    rows = []
    fasta_seen = {}
    errors = []
    jobs = []

    for i, row in manifest.reset_index(drop=True).iterrows():
        seq = clean_seq(row.get("selected_wt_sequence"))
        seq_md5 = row.get("seq_md5") if isinstance(row.get("seq_md5"), str) else md5_seq(seq)
        seq_id = f"saprot_{len(fasta_seen) + 1:04d}_{str(seq_md5)[:10]}" if seq_md5 not in fasta_seen else fasta_seen[seq_md5]
        fasta_seen[seq_md5] = seq_id

        chosen = choose_structure(row, af2_lookup, args.struct_dir, args.prefer)

        single_chain_path = struct_out / f"{seq_id}.pdb"
        extract_status = "not_run"
        parser_mode = ""
        actual_chain_id = ""

        try:
            if chosen["source_structure_path"] and os.path.exists(chosen["source_structure_path"]):
                info = extract_single_chain_pdb(
                    input_path=chosen["source_structure_path"],
                    chain_id=str(chosen["source_chain_id"]),
                    output_path=str(single_chain_path),
                )
                extract_status = "ok"
                parser_mode = info["parser_mode"]
                actual_chain_id = info["actual_chain_id"]
            else:
                extract_status = "missing_source_structure"
        except Exception as e:
            extract_status = "error"
            errors.append({
                "seq_id": seq_id,
                "DMS_name": row.get("DMS_name"),
                "pdb_id": row.get("pdb_id"),
                "pdb_chain_id": row.get("pdb_chain_id"),
                "source_structure_path": chosen["source_structure_path"],
                "error": str(e),
            })

        jobs.append({
            "seq_id": seq_id,
            "DMS_name": row.get("DMS_name"),
            "pdb_id": row.get("pdb_id"),
            "pdb_chain_id": row.get("pdb_chain_id"),
            "structure_mode": chosen["structure_mode"],
            "single_chain_pdb": str(single_chain_path) if extract_status == "ok" else "",
            "foldseek_prefix": str(out_dir / "foldseek_3di" / seq_id),
            "extract_status": extract_status,
        })

        rows.append({
            "seq_id": seq_id,
            "DMS_name": row.get("DMS_name"),
            "pdb_id": row.get("pdb_id"),
            "pdb_chain_id": row.get("pdb_chain_id"),
            "seq_md5": seq_md5,
            "sequence_length": len(seq),
            "start_pos": row.get("start_pos_from_ref"),
            "n_dms_sites": row.get("n_dms_sites"),
            "n_dms_PDB": row.get("n_dms_PDB"),
            "n_dms_AF2_fill": row.get("n_dms_AF2_fill"),
            "n_dms_residue_only": row.get("n_dms_residue_only"),
            "structure_mode": chosen["structure_mode"],
            "source_structure_path": chosen["source_structure_path"],
            "source_chain_id": chosen["source_chain_id"],
            "single_chain_pdb": str(single_chain_path) if extract_status == "ok" else "",
            "extract_status": extract_status,
            "parser_mode": parser_mode,
            "actual_chain_id": actual_chain_id,
            "reason": chosen["reason"],
            "selected_wt_sequence": seq,
        })

    out_manifest = pd.DataFrame(rows)
    out_manifest.to_csv(out_dir / "saprot_input_manifest.csv", index=False)

    # FASTA unique sequences.
    with open(out_dir / "saprot_unique_sequences.fasta", "w") as f:
        for seq_md5, seq_id in fasta_seen.items():
            seq = out_manifest[out_manifest["seq_id"] == seq_id]["selected_wt_sequence"].iloc[0]
            f.write(f">{seq_id}\n")
            f.write(wrap_fasta(seq) + "\n")

    # Jobs.
    jobs_df = pd.DataFrame(jobs)
    jobs_df.to_csv(out_dir / "saprot_structure_jobs.tsv", sep="\t", index=False)

    # Mask positions: residue_only positions should not be trusted as structure tokens.
    seq_map = out_manifest[["DMS_name", "pdb_id", "pdb_chain_id", "seq_id"]].drop_duplicates()
    mask = final.merge(seq_map, on=["DMS_name", "pdb_id", "pdb_chain_id"], how="left")
    mask = mask[mask["final_source"] == "residue_only"].copy()
    keep_cols = [
        "seq_id", "DMS_name", "pdb_id", "pdb_chain_id", "wt_local_pos", "fasta_pos",
        "wt_aa", "is_dms_site", "final_source", "af2_plddt"
    ]
    keep_cols = [c for c in keep_cols if c in mask.columns]
    mask[keep_cols].to_csv(out_dir / "saprot_mask_positions.tsv", sep="\t", index=False)

    # Foldseek shell.
    foldseek_dir = out_dir / "foldseek_3di"
    foldseek_dir.mkdir(exist_ok=True)
    with open(out_dir / "run_foldseek_saprot.sh", "w") as f:
        f.write("#!/usr/bin/env bash\nset -euo pipefail\n\n")
        f.write("mkdir -p " + str(foldseek_dir) + "\n\n")
        f.write("# Check command availability first:\n")
        f.write("# foldseek version\n\n")
        for _, r in jobs_df.iterrows():
            if r["extract_status"] != "ok":
                continue
            # This is the common SaProt/Foldseek 3Di extraction entry.
            # Depending on your Foldseek version, output format may vary.
            f.write(f"foldseek structureto3didescriptor {r['single_chain_pdb']} {r['foldseek_prefix']} --threads 4\n")

    if errors:
        pd.DataFrame(errors).to_csv(out_dir / "saprot_structure_extract_errors.csv", index=False)

    print("[OK] Wrote", out_dir / "saprot_input_manifest.csv")
    print("[OK] Wrote", out_dir / "saprot_unique_sequences.fasta")
    print("[OK] Wrote", out_dir / "saprot_structure_jobs.tsv")
    print("[OK] Wrote", out_dir / "saprot_mask_positions.tsv")
    print("[OK] Wrote", out_dir / "run_foldseek_saprot.sh")
    if errors:
        print("[WARN] Some chain extraction errors:", out_dir / "saprot_structure_extract_errors.csv")

    print("\nStructure mode counts:")
    print(out_manifest["structure_mode"].value_counts(dropna=False))
    print("\nExtraction status counts:")
    print(out_manifest["extract_status"].value_counts(dropna=False))


if __name__ == "__main__":
    main()
